name: Sahamyab Archive

on:
  schedule:
    # هر 4 ساعت یکبار (روزانه 6 مرتبه)
    - cron: '0 13 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: mkdir -p snapshots

      - run: python scrape.py

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add snapshots/*.json

          git diff --cached --quiet || (
            git commit -m "Snapshot $(date -u '+%Y-%m-%d %H:%M')"
            git push
          )
